name: Node.js Package Publish

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: DevToolz.Library.ts # ajusta para subpasta onde está o tsconfig.json
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm ci

      - name: Executar testes
        run: npm test

  build:
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: DevToolz.Library.ts
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm ci

      - name: Executar build
        run: npm run build

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: DevToolz.Library.ts
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js com registry do GitHub
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/

      - name: Instalar dependências
        run: npm ci

      - name: Publicar no GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_KEY }}
